version: "3"

services:
  caddy:
    build:
      context: .
      dockerfile: caddy/Dockerfile
#    network_mode: host
    command: caddy run --resume -config /etc/caddy/Caddyfile
    ports:
      - "81:81"
      - "80:80"
      - "443:443"
      - "2019:2019"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./.tmp/caddy:/config/caddy
      - ./.tmp/data:/data